from dataclasses import dataclass
from typing import Optional

@dataclass
class DistillationEntry:
    """
    Contains data for distillation process. If the reasoning generated by the model is correct,
    then another model (or another instance of the same model) should be able to generate the same solution.
    Args:
        question: str -- SQL problem/question
        schema: str -- Database schema related to the question
        gold_solution: str -- Provided ground truth solution
        reasoning: str -- Logical reasoning steps generated by the model
        verification_solution: str -- Solution generated by another model given the reasoning
        isVerified: Optional[bool] = None -- Whether the verification_solution is correct
    """
    teacher_model_name: str
    question: str
    schema: str
    gold_solution: str
    reasoning: str
    verification_solution: str
    isVerified: Optional[bool] = None